---
- name: Create user 'dan' on OCI compute instance
  hosts: all
  become: true # Run tasks as root using privilege escalation
  vars:
    new_user: "dan"

  tasks:
    - name: Ensure the user 'dan' exists
      user:
        name: "{{ new_user }}"
        state: present
        shell: /bin/bash
        create_home: true

    - name: Set authorized key defining key options
      ansible.posix.authorized_key:
        user: "{{ new_user }}"
        state: present
        key: "{{ lookup('file', 'pub_key') }}"
      when: lookup('file', 'pub_key', errors='ignore')

    - name: Add 'dan' to sudoers with no password prompt
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: "^{{ new_user }}"
        line: "{{ new_user }} ALL=(ALL) NOPASSWD:ALL"
        validate: "visudo -cf %s"
