---
- name: "DEPLOY WAZUH AGENT 4.10.1-1 ON Oracle RedHat Linux ENDPOINTS"
  hosts: all
  become: yes
  remote_user: opc
  vars:
    wazuh_manager_ip: "132.145.149.232"

  tasks:
    - name: "0 - Download the Wazuh agent on the OCI instance"
      tags: download_wazuh_agent
      ansible.builtin.get_url:
        url: https://packages.wazuh.com/4.x/yum/wazuh-agent-4.10.1-1.x86_64.rpm
        dest: /tmp
        mode: "0774"

    - name: "1 - Deploy the Wazuh agent on the Oracle endpoint"
      ansible.builtin.shell: WAZUH_MANAGER={{wazuh_manager_ip}} WAZUH_AGENT_NAME="Oracle-RH-Linux" sudo rpm -ivh /tmp/wazuh-agent-4.10.1-1.x86_64.rpm
      when: ansible_os_family == "RedHat"

    - name: "2 - Configure Wazuh Manager IP in ossec.conf"
      replace:
        path: /var/ossec/etc/ossec.conf
        regexp: "<address>.*</address>"
        replace: "<address>{{ wazuh_manager_ip }}</address>"
      notify: Restart Wazuh Agent

    - name: "3 - Ensure firewall allows agent communication"
      firewalld:
        port: 1514/tcp
        permanent: yes
        state: enabled
      notify: Reload Firewall

  handlers:
    - name: Restart Wazuh Agent
      service:
        name: wazuh-agent
        state: restarted

    - name: Reload Firewall
      command: firewall-cmd --reload
